# 1. Tomcat Server Setting
server:
  port: 80
  servlet:
    context-path: /
    encoding:
      charset: utf-8

# 2. SpringBoot Environment Setting
spring:

  datasource:
    #    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    #    url: jdbc:log4jdbc:mysql://127.1.0.1:3306/smdb?characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/stest?characterEncoding=utf8
    username: suser
    password: 111111

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      '[hibernate.format_sql]': true
  output:
    ansi:
      enabled: always

# 4. Logging Setting
logging:
  level:
    '[org.springframework.web]': INFO
    '[org.hibernate]': INFO
  #  error > info > debug

# 5. Application Environment Setting