spring:
  profiles:
    active: dev

  application:
    name: gwms

  datasource:
#    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://10.5.240.229:23306/gwms
#    username: gwmsuser
#    password: gwms12#$

    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/gwms  # H2 접속 정보
    username: sa  # H2 접속 시 입력할 username 정보 (원하는 것으로 입력)
    password:  # H2 접속 시 입력할 password 정보 (원하는 것으로 입력)

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

