spring:
  profiles:
    active: dev

  application:
    name: authorization-server

#  datasource:
#    hikari:
#      jdbc-url: jdbc:h2:file:C:/h2db/hmgesgdb
#      driver-class-name: org.h2.Driver
#      username: sa
#      password:
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true

  thymeleaf:
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
    cache: false
#
#  datasource:
#    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://10.5.240.229:23306/hmg_esg_dev
#    username: esguser
#    password: esg12#$
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true

server:
  port: 1234